### ISSUE TITLE
Graag een README

### ISSUE THREAD

**Issue by bartvanderwal** [HANICA/waterworld#1]
Goed werk @meronbrouwer!

Lijkt mij heel goed om zo WaterWorld en de OOPG engine op te splitsen. Zo voorkom je ook dat mensen de engine onaangekondigd gaan aanpassen. En is meteen een intro into packagement management. Dit is echter wel allemaal extra, en kun je niet verplichten, dus studenten moeten dan wel een simpele handleiding kunnen volgen zonder veel begrip.

Als Maven newbie kan ik zelf ook nog wel in de README ook een beschrijving gebruiken, die me vertelt hoe ik dit aan de praat krijg. Als ik de `pom.xml` bekijk zie ik (uiteraard) een dependency op OOPG. Maar het lijkt erop dat je er zelf voor moet zorgen dat deze ook lokaal (als `.jar`) aanwezig is.

Ik kom uit NPM land, waar het relatief makkelijk is om zelf een [package](https://www.npmjs.com/package/check-vs-includes) toe te voegen in de NPM repository en dan `npm install` al je dependency problemen te laten oplossen. Maven kent wel een 'central repository', maar die is een stuk minder open. Processing staat hier overigens [nog wel in](https://mvnrepository.com/artifact/org.processing/core/3.3.7) (ook de [v2.2 versie](https://mvnrepository.com/artifact/org.processing/core/2.2.1) die OOPG nu (nog) gebruikt)). 

Ik zal me eens in [Maven verdiepen](https://www.youtube.com/watch?v=Fe6lrsPmseo) of ik dit zelf kan uitvogelen en de README uitbreiden.

**Comment by bartvanderwal** [comment]
@meronbrouwer Het werkt bij mij; as in: ik kwan waterworld runnen door deze `waterworld` repo lokaal te clonen en importeren in Eclipse (analoog aan hoe ik heb nu uitgeschreven in OOPG 'up-and-running).

Maar nu zit er een .jar van oopg als dependency in de pom. Is het niet mogelijk om in plaats daarvan direct de oopg github te gebruiken als dependency, zodat studenten altijd met de laatste (stabiele) versie werken? Direct GitHub gebruiken had Rody het ook had gedaan met een raw.github.com URL met oopg, maar dan direct op basis van de huidige github.com/HANICA/oopg (wellicht moet die dan openbaar worden).

Op basis van deze SO post kan JitPack dit doen (dan indirect doordat vanaf GitHub repo maakt JitPack er alsnog een .jar van, en wellicht moeten we dan ook goed versie instellen)
https://stackoverflow.com/questions/20161602/loading-maven-dependencies-from-github

**Comment by meronbrouwer** [comment]
@bartvanderwal  De manier van clonen vereist kennis van git. Daar kunnen we niet vanuit gaan. Paksha heeft getest of de zip bruikbaar is en dat ging prima.

De jar in de lib folder is even een pragmatische aanpak. Het kan prima dat we deze via github hosten, maar dat is iets meer werk. En ik ben nu al door mijn uren heen 🙁

**Comment by meronbrouwer** [comment]
ik heb er nog even aan gezeten en HANICA/WaterWorld maakt nu via de pom gebruik van de jar die HANICA/oopg maakt. Deze wordt door HANICA/WaterWorld direct uit Github van HANICA/oopg gehaald.
